export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const SEARCH_VIDEOGAMES = "SEARCH_VIDEOGAMES";
export const ORDER_VIDEOGAMES = "ORDER_VIDEOGAMES";
export const GET_VIDEOGAME = "GET_VIDEOGAME";
export const GET_ALL_GENRES = "GET_ALL_GENRES";

export const ASCENDENTE = "ASCENDENTE"
export const DESCENDENTE = "DESCENDENTE"